// DrawParty — Database Seed
// Populates all lookup/reference tables required for the app to function.
// Run with: npx prisma db seed

import { PrismaClient } from "../src/generated/prisma";
import { PrismaNeon } from "@prisma/adapter-neon";
import "dotenv/config";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  // ── FriendshipStatus ──────────────────────────────────────────────────────
  await prisma.friendshipStatus.createMany({
    data: [
      { id: "PENDING",  slug: "pending",  label: "En attente" },
      { id: "ACCEPTED", slug: "accepted", label: "Accepté" },
      { id: "DECLINED", slug: "declined", label: "Refusé" },
      { id: "BLOCKED",  slug: "blocked",  label: "Bloqué" },
    ],
    skipDuplicates: true,
  });

  // ── GameMode ──────────────────────────────────────────────────────────────
  await prisma.gameMode.createMany({
    data: [
      { id: "GARTIC_PHONE", slug: "gartic-phone", label: "Gartic Phone" },
      { id: "SKRIBBL",      slug: "skribbl",      label: "Skribbl" },
    ],
    skipDuplicates: true,
  });

  // ── RoomStatus ────────────────────────────────────────────────────────────
  await prisma.roomStatus.createMany({
    data: [
      { id: "WAITING",  label: "En attente" },
      { id: "PLAYING",  label: "En cours" },
      { id: "FINISHED", label: "Terminé" },
    ],
    skipDuplicates: true,
  });

  // ── RoomPlayerStatus ──────────────────────────────────────────────────────
  await prisma.roomPlayerStatus.createMany({
    data: [
      { id: "CONNECTED",    label: "Connecté" },
      { id: "DISCONNECTED", label: "Déconnecté" },
      { id: "KICKED",       label: "Exclu" },
    ],
    skipDuplicates: true,
  });

  // ── GarticGamePhase ───────────────────────────────────────────────────────
  await prisma.garticGamePhase.createMany({
    data: [
      { id: "PROMPT",   label: "Écriture" },
      { id: "DRAW",     label: "Dessin" },
      { id: "DESCRIBE", label: "Description" },
      { id: "REWIND",   label: "Rétrospective" },
      { id: "FINISHED", label: "Terminé" },
    ],
    skipDuplicates: true,
  });

  // ── GarticStepType ────────────────────────────────────────────────────────
  await prisma.garticStepType.createMany({
    data: [
      { id: "PROMPT",   label: "Prompt" },
      { id: "DRAW",     label: "Dessin" },
      { id: "DESCRIBE", label: "Description" },
    ],
    skipDuplicates: true,
  });

  // ── SkribblGamePhase ──────────────────────────────────────────────────────
  await prisma.skribblGamePhase.createMany({
    data: [
      { id: "WAITING",      label: "En attente" },
      { id: "PICKING_WORD", label: "Choix du mot" },
      { id: "DRAWING",      label: "Dessin en cours" },
      { id: "ROUND_END",    label: "Tour terminé" },
      { id: "FINISHED",     label: "Fini" },
    ],
    skipDuplicates: true,
  });

  // ── AIDrawMode ────────────────────────────────────────────────────────────
  await prisma.aIDrawMode.createMany({
    data: [
      { id: "turn",   label: "Tour par tour" },
      { id: "shared", label: "Simultané" },
    ],
    skipDuplicates: true,
  });

  // ── ChainStepRating ───────────────────────────────────────────────────────
  await prisma.chainStepRating.createMany({
    data: [
      { id: "GREEN",  label: "Vert" },
      { id: "YELLOW", label: "Jaune" },
      { id: "RED",    label: "Rouge" },
    ],
    skipDuplicates: true,
  });

  // ── GarticAIGamePhase ─────────────────────────────────────────────────────
  await prisma.garticAIGamePhase.createMany({
    data: [
      { id: "DRAWING",      label: "Dessin" },
      { id: "AI_JUDGING",   label: "Jugement IA" },
      { id: "ROUND_RESULT", label: "Résultat du tour" },
      { id: "GAME_OVER",    label: "Partie terminée" },
    ],
    skipDuplicates: true,
  });

  // ── WordDifficulty ────────────────────────────────────────────────────────
  await prisma.wordDifficulty.createMany({
    data: [
      { id: "EASY",   label: "Facile" },
      { id: "MEDIUM", label: "Moyen" },
      { id: "HARD",   label: "Difficile" },
    ],
    skipDuplicates: true,
  });

  // ── Words ─────────────────────────────────────────────────────────────────
  await prisma.word.createMany({
    data: [
      // ── Animals (25) ──────────────────────────────────────────────────────
      { text: "cat",        category: "animals", difficultyId: "EASY" },
      { text: "dog",        category: "animals", difficultyId: "EASY" },
      { text: "fish",       category: "animals", difficultyId: "EASY" },
      { text: "bird",       category: "animals", difficultyId: "EASY" },
      { text: "frog",       category: "animals", difficultyId: "EASY" },
      { text: "lion",       category: "animals", difficultyId: "EASY" },
      { text: "bear",       category: "animals", difficultyId: "EASY" },
      { text: "wolf",       category: "animals", difficultyId: "EASY" },
      { text: "turtle",     category: "animals", difficultyId: "EASY" },
      { text: "parrot",     category: "animals", difficultyId: "EASY" },
      { text: "elephant",   category: "animals", difficultyId: "MEDIUM" },
      { text: "giraffe",    category: "animals", difficultyId: "MEDIUM" },
      { text: "penguin",    category: "animals", difficultyId: "MEDIUM" },
      { text: "dolphin",    category: "animals", difficultyId: "MEDIUM" },
      { text: "gorilla",    category: "animals", difficultyId: "MEDIUM" },
      { text: "zebra",      category: "animals", difficultyId: "MEDIUM" },
      { text: "kangaroo",   category: "animals", difficultyId: "MEDIUM" },
      { text: "octopus",    category: "animals", difficultyId: "MEDIUM" },
      { text: "crocodile",  category: "animals", difficultyId: "MEDIUM" },
      { text: "tiger",      category: "animals", difficultyId: "MEDIUM" },
      { text: "platypus",   category: "animals", difficultyId: "HARD" },
      { text: "chameleon",  category: "animals", difficultyId: "HARD" },
      { text: "axolotl",    category: "animals", difficultyId: "HARD" },
      { text: "narwhal",    category: "animals", difficultyId: "HARD" },
      { text: "capybara",   category: "animals", difficultyId: "HARD" },

      // ── Objects (25) ──────────────────────────────────────────────────────
      { text: "chair",      category: "objects", difficultyId: "EASY" },
      { text: "clock",      category: "objects", difficultyId: "EASY" },
      { text: "book",       category: "objects", difficultyId: "EASY" },
      { text: "lamp",       category: "objects", difficultyId: "EASY" },
      { text: "key",        category: "objects", difficultyId: "EASY" },
      { text: "mirror",     category: "objects", difficultyId: "EASY" },
      { text: "ladder",     category: "objects", difficultyId: "EASY" },
      { text: "shovel",     category: "objects", difficultyId: "EASY" },
      { text: "hammer",     category: "objects", difficultyId: "EASY" },
      { text: "lantern",    category: "objects", difficultyId: "EASY" },
      { text: "umbrella",   category: "objects", difficultyId: "MEDIUM" },
      { text: "telescope",  category: "objects", difficultyId: "MEDIUM" },
      { text: "compass",    category: "objects", difficultyId: "MEDIUM" },
      { text: "backpack",   category: "objects", difficultyId: "MEDIUM" },
      { text: "scissors",   category: "objects", difficultyId: "MEDIUM" },
      { text: "globe",      category: "objects", difficultyId: "MEDIUM" },
      { text: "anchor",     category: "objects", difficultyId: "MEDIUM" },
      { text: "trophy",     category: "objects", difficultyId: "MEDIUM" },
      { text: "hourglass",  category: "objects", difficultyId: "MEDIUM" },
      { text: "magnet",     category: "objects", difficultyId: "MEDIUM" },
      { text: "microscope", category: "objects", difficultyId: "HARD" },
      { text: "abacus",     category: "objects", difficultyId: "HARD" },
      { text: "periscope",  category: "objects", difficultyId: "HARD" },
      { text: "protractor", category: "objects", difficultyId: "HARD" },
      { text: "metronome",  category: "objects", difficultyId: "HARD" },

      // ── Food (25) ─────────────────────────────────────────────────────────
      { text: "pizza",      category: "food", difficultyId: "EASY" },
      { text: "bread",      category: "food", difficultyId: "EASY" },
      { text: "apple",      category: "food", difficultyId: "EASY" },
      { text: "cake",       category: "food", difficultyId: "EASY" },
      { text: "egg",        category: "food", difficultyId: "EASY" },
      { text: "sushi",      category: "food", difficultyId: "EASY" },
      { text: "taco",       category: "food", difficultyId: "EASY" },
      { text: "waffle",     category: "food", difficultyId: "EASY" },
      { text: "donut",      category: "food", difficultyId: "EASY" },
      { text: "popcorn",    category: "food", difficultyId: "EASY" },
      { text: "avocado",    category: "food", difficultyId: "MEDIUM" },
      { text: "spaghetti",  category: "food", difficultyId: "MEDIUM" },
      { text: "pretzel",    category: "food", difficultyId: "MEDIUM" },
      { text: "croissant",  category: "food", difficultyId: "MEDIUM" },
      { text: "burrito",    category: "food", difficultyId: "MEDIUM" },
      { text: "strawberry", category: "food", difficultyId: "MEDIUM" },
      { text: "pineapple",  category: "food", difficultyId: "MEDIUM" },
      { text: "mushroom",   category: "food", difficultyId: "MEDIUM" },
      { text: "sandwich",   category: "food", difficultyId: "MEDIUM" },
      { text: "lemonade",   category: "food", difficultyId: "MEDIUM" },
      { text: "quesadilla", category: "food", difficultyId: "HARD" },
      { text: "bruschetta", category: "food", difficultyId: "HARD" },
      { text: "charcuterie",category: "food", difficultyId: "HARD" },
      { text: "profiterole",category: "food", difficultyId: "HARD" },
      { text: "ratatouille",category: "food", difficultyId: "HARD" },

      // ── Places (25) ───────────────────────────────────────────────────────
      { text: "beach",      category: "places", difficultyId: "EASY" },
      { text: "forest",     category: "places", difficultyId: "EASY" },
      { text: "school",     category: "places", difficultyId: "EASY" },
      { text: "bridge",     category: "places", difficultyId: "EASY" },
      { text: "island",     category: "places", difficultyId: "EASY" },
      { text: "castle",     category: "places", difficultyId: "EASY" },
      { text: "harbor",     category: "places", difficultyId: "EASY" },
      { text: "desert",     category: "places", difficultyId: "EASY" },
      { text: "village",    category: "places", difficultyId: "EASY" },
      { text: "stadium",    category: "places", difficultyId: "EASY" },
      { text: "volcano",    category: "places", difficultyId: "MEDIUM" },
      { text: "lighthouse", category: "places", difficultyId: "MEDIUM" },
      { text: "library",    category: "places", difficultyId: "MEDIUM" },
      { text: "waterfall",  category: "places", difficultyId: "MEDIUM" },
      { text: "cathedral",  category: "places", difficultyId: "MEDIUM" },
      { text: "canyon",     category: "places", difficultyId: "MEDIUM" },
      { text: "glacier",    category: "places", difficultyId: "MEDIUM" },
      { text: "dungeon",    category: "places", difficultyId: "MEDIUM" },
      { text: "temple",     category: "places", difficultyId: "MEDIUM" },
      { text: "meadow",     category: "places", difficultyId: "MEDIUM" },
      { text: "colosseum",  category: "places", difficultyId: "HARD" },
      { text: "observatory",category: "places", difficultyId: "HARD" },
      { text: "archipelago",category: "places", difficultyId: "HARD" },
      { text: "mausoleum",  category: "places", difficultyId: "HARD" },
      { text: "acropolis",  category: "places", difficultyId: "HARD" },

      // ── Actions (25) — new category ───────────────────────────────────────
      { text: "run",        category: "actions", difficultyId: "EASY" },
      { text: "jump",       category: "actions", difficultyId: "EASY" },
      { text: "swim",       category: "actions", difficultyId: "EASY" },
      { text: "fly",        category: "actions", difficultyId: "EASY" },
      { text: "climb",      category: "actions", difficultyId: "EASY" },
      { text: "dance",      category: "actions", difficultyId: "EASY" },
      { text: "sing",       category: "actions", difficultyId: "EASY" },
      { text: "cook",       category: "actions", difficultyId: "EASY" },
      { text: "laugh",      category: "actions", difficultyId: "EASY" },
      { text: "sleep",      category: "actions", difficultyId: "EASY" },
      { text: "paint",      category: "actions", difficultyId: "MEDIUM" },
      { text: "write",      category: "actions", difficultyId: "MEDIUM" },
      { text: "build",      category: "actions", difficultyId: "MEDIUM" },
      { text: "throw",      category: "actions", difficultyId: "MEDIUM" },
      { text: "catch",      category: "actions", difficultyId: "MEDIUM" },
      { text: "push",       category: "actions", difficultyId: "MEDIUM" },
      { text: "kick",       category: "actions", difficultyId: "MEDIUM" },
      { text: "wave",       category: "actions", difficultyId: "MEDIUM" },
      { text: "dig",        category: "actions", difficultyId: "MEDIUM" },
      { text: "spin",       category: "actions", difficultyId: "MEDIUM" },
      { text: "crawl",      category: "actions", difficultyId: "HARD" },
      { text: "whisper",    category: "actions", difficultyId: "HARD" },
      { text: "shout",      category: "actions", difficultyId: "HARD" },
      { text: "meditate",   category: "actions", difficultyId: "HARD" },
      { text: "juggle",     category: "actions", difficultyId: "HARD" },

      // ── Nature (25) — new category ────────────────────────────────────────
      { text: "mountain",   category: "nature", difficultyId: "EASY" },
      { text: "river",      category: "nature", difficultyId: "EASY" },
      { text: "ocean",      category: "nature", difficultyId: "EASY" },
      { text: "cave",       category: "nature", difficultyId: "EASY" },
      { text: "rainbow",    category: "nature", difficultyId: "EASY" },
      { text: "sunset",     category: "nature", difficultyId: "EASY" },
      { text: "fog",        category: "nature", difficultyId: "EASY" },
      { text: "frost",      category: "nature", difficultyId: "EASY" },
      { text: "tide",       category: "nature", difficultyId: "EASY" },
      { text: "petal",      category: "nature", difficultyId: "EASY" },
      { text: "thunder",    category: "nature", difficultyId: "MEDIUM" },
      { text: "lightning",  category: "nature", difficultyId: "MEDIUM" },
      { text: "tornado",    category: "nature", difficultyId: "MEDIUM" },
      { text: "aurora",     category: "nature", difficultyId: "MEDIUM" },
      { text: "coral",      category: "nature", difficultyId: "MEDIUM" },
      { text: "cactus",     category: "nature", difficultyId: "MEDIUM" },
      { text: "cliff",      category: "nature", difficultyId: "MEDIUM" },
      { text: "dune",       category: "nature", difficultyId: "MEDIUM" },
      { text: "swamp",      category: "nature", difficultyId: "MEDIUM" },
      { text: "vine",       category: "nature", difficultyId: "MEDIUM" },
      { text: "valley",     category: "nature", difficultyId: "HARD" },
      { text: "tundra",     category: "nature", difficultyId: "HARD" },
      { text: "marsh",      category: "nature", difficultyId: "HARD" },
      { text: "pebble",     category: "nature", difficultyId: "HARD" },
      { text: "moss",       category: "nature", difficultyId: "HARD" },

      // ── Sports (25) — new category ────────────────────────────────────────
      { text: "soccer",     category: "sports", difficultyId: "EASY" },
      { text: "tennis",     category: "sports", difficultyId: "EASY" },
      { text: "swimming",   category: "sports", difficultyId: "EASY" },
      { text: "cycling",    category: "sports", difficultyId: "EASY" },
      { text: "boxing",     category: "sports", difficultyId: "EASY" },
      { text: "hockey",     category: "sports", difficultyId: "EASY" },
      { text: "golf",       category: "sports", difficultyId: "EASY" },
      { text: "skiing",     category: "sports", difficultyId: "EASY" },
      { text: "diving",     category: "sports", difficultyId: "EASY" },
      { text: "rowing",     category: "sports", difficultyId: "EASY" },
      { text: "basketball", category: "sports", difficultyId: "MEDIUM" },
      { text: "volleyball", category: "sports", difficultyId: "MEDIUM" },
      { text: "archery",    category: "sports", difficultyId: "MEDIUM" },
      { text: "surfing",    category: "sports", difficultyId: "MEDIUM" },
      { text: "fencing",    category: "sports", difficultyId: "MEDIUM" },
      { text: "badminton",  category: "sports", difficultyId: "MEDIUM" },
      { text: "bowling",    category: "sports", difficultyId: "MEDIUM" },
      { text: "marathon",   category: "sports", difficultyId: "MEDIUM" },
      { text: "snowboard",  category: "sports", difficultyId: "MEDIUM" },
      { text: "wrestling",  category: "sports", difficultyId: "MEDIUM" },
      { text: "gymnastics", category: "sports", difficultyId: "HARD" },
      { text: "skateboard", category: "sports", difficultyId: "HARD" },
      { text: "triathlon",  category: "sports", difficultyId: "HARD" },
      { text: "javelin",    category: "sports", difficultyId: "HARD" },
      { text: "hurdles",    category: "sports", difficultyId: "HARD" },

      // ── Clothing (25) — new category ──────────────────────────────────────
      { text: "hat",        category: "clothing", difficultyId: "EASY" },
      { text: "shirt",      category: "clothing", difficultyId: "EASY" },
      { text: "shoes",      category: "clothing", difficultyId: "EASY" },
      { text: "jacket",     category: "clothing", difficultyId: "EASY" },
      { text: "scarf",      category: "clothing", difficultyId: "EASY" },
      { text: "gloves",     category: "clothing", difficultyId: "EASY" },
      { text: "dress",      category: "clothing", difficultyId: "EASY" },
      { text: "boots",      category: "clothing", difficultyId: "EASY" },
      { text: "socks",      category: "clothing", difficultyId: "EASY" },
      { text: "belt",       category: "clothing", difficultyId: "EASY" },
      { text: "sweater",    category: "clothing", difficultyId: "MEDIUM" },
      { text: "trousers",   category: "clothing", difficultyId: "MEDIUM" },
      { text: "vest",       category: "clothing", difficultyId: "MEDIUM" },
      { text: "tie",        category: "clothing", difficultyId: "MEDIUM" },
      { text: "raincoat",   category: "clothing", difficultyId: "MEDIUM" },
      { text: "sneakers",   category: "clothing", difficultyId: "MEDIUM" },
      { text: "sandals",    category: "clothing", difficultyId: "MEDIUM" },
      { text: "hoodie",     category: "clothing", difficultyId: "MEDIUM" },
      { text: "leggings",   category: "clothing", difficultyId: "MEDIUM" },
      { text: "uniform",    category: "clothing", difficultyId: "MEDIUM" },
      { text: "cape",       category: "clothing", difficultyId: "HARD" },
      { text: "tuxedo",     category: "clothing", difficultyId: "HARD" },
      { text: "kimono",     category: "clothing", difficultyId: "HARD" },
      { text: "beret",      category: "clothing", difficultyId: "HARD" },
      { text: "mitten",     category: "clothing", difficultyId: "HARD" },

      // ── Extra English — animals ────────────────────────────────────────────
      { text: "rabbit",     category: "animals", difficultyId: "EASY" },
      { text: "horse",      category: "animals", difficultyId: "EASY" },
      { text: "cow",        category: "animals", difficultyId: "EASY" },
      { text: "pig",        category: "animals", difficultyId: "EASY" },
      { text: "sheep",      category: "animals", difficultyId: "EASY" },
      { text: "chicken",    category: "animals", difficultyId: "EASY" },
      { text: "duck",       category: "animals", difficultyId: "EASY" },
      { text: "goose",      category: "animals", difficultyId: "EASY" },
      { text: "swan",       category: "animals", difficultyId: "EASY" },
      { text: "snake",      category: "animals", difficultyId: "EASY" },
      { text: "monkey",     category: "animals", difficultyId: "EASY" },
      { text: "camel",      category: "animals", difficultyId: "EASY" },
      { text: "eagle",      category: "animals", difficultyId: "EASY" },
      { text: "owl",        category: "animals", difficultyId: "EASY" },
      { text: "bat",        category: "animals", difficultyId: "EASY" },
      { text: "bee",        category: "animals", difficultyId: "EASY" },
      { text: "ant",        category: "animals", difficultyId: "EASY" },
      { text: "flamingo",   category: "animals", difficultyId: "MEDIUM" },
      { text: "peacock",    category: "animals", difficultyId: "MEDIUM" },
      { text: "butterfly",  category: "animals", difficultyId: "MEDIUM" },
      { text: "crab",       category: "animals", difficultyId: "MEDIUM" },
      { text: "lobster",    category: "animals", difficultyId: "MEDIUM" },
      { text: "jellyfish",  category: "animals", difficultyId: "MEDIUM" },
      { text: "snail",      category: "animals", difficultyId: "MEDIUM" },
      { text: "deer",       category: "animals", difficultyId: "MEDIUM" },
      { text: "raccoon",    category: "animals", difficultyId: "MEDIUM" },
      { text: "fox",        category: "animals", difficultyId: "MEDIUM" },
      { text: "seal",       category: "animals", difficultyId: "MEDIUM" },
      { text: "orca",       category: "animals", difficultyId: "MEDIUM" },
      { text: "panda",      category: "animals", difficultyId: "MEDIUM" },
      { text: "moose",      category: "animals", difficultyId: "HARD" },
      { text: "walrus",     category: "animals", difficultyId: "HARD" },
      { text: "rhinoceros", category: "animals", difficultyId: "HARD" },
      { text: "hippopotamus", category: "animals", difficultyId: "HARD" },
      { text: "chimpanzee", category: "animals", difficultyId: "HARD" },
      { text: "salamander", category: "animals", difficultyId: "HARD" },

      // ── Extra English — objects ────────────────────────────────────────────
      { text: "phone",      category: "objects", difficultyId: "EASY" },
      { text: "computer",   category: "objects", difficultyId: "EASY" },
      { text: "camera",     category: "objects", difficultyId: "EASY" },
      { text: "guitar",     category: "objects", difficultyId: "EASY" },
      { text: "piano",      category: "objects", difficultyId: "EASY" },
      { text: "map",        category: "objects", difficultyId: "EASY" },
      { text: "sword",      category: "objects", difficultyId: "EASY" },
      { text: "crown",      category: "objects", difficultyId: "EASY" },
      { text: "shield",     category: "objects", difficultyId: "EASY" },
      { text: "candle",     category: "objects", difficultyId: "EASY" },
      { text: "bicycle",    category: "objects", difficultyId: "MEDIUM" },
      { text: "rocket",     category: "objects", difficultyId: "MEDIUM" },
      { text: "diamond",    category: "objects", difficultyId: "MEDIUM" },
      { text: "treasure",   category: "objects", difficultyId: "MEDIUM" },
      { text: "microphone", category: "objects", difficultyId: "MEDIUM" },
      { text: "headphones", category: "objects", difficultyId: "MEDIUM" },
      { text: "sunglasses", category: "objects", difficultyId: "MEDIUM" },
      { text: "windmill",   category: "objects", difficultyId: "MEDIUM" },
      { text: "television", category: "objects", difficultyId: "MEDIUM" },
      { text: "parachute",  category: "objects", difficultyId: "HARD" },
      { text: "submarine",  category: "objects", difficultyId: "HARD" },
      { text: "helicopter", category: "objects", difficultyId: "HARD" },
      { text: "catapult",   category: "objects", difficultyId: "HARD" },
      { text: "calculator", category: "objects", difficultyId: "HARD" },

      // ── Extra English — food ───────────────────────────────────────────────
      { text: "banana",     category: "food", difficultyId: "EASY" },
      { text: "orange",     category: "food", difficultyId: "EASY" },
      { text: "grape",      category: "food", difficultyId: "EASY" },
      { text: "cherry",     category: "food", difficultyId: "EASY" },
      { text: "peach",      category: "food", difficultyId: "EASY" },
      { text: "lemon",      category: "food", difficultyId: "EASY" },
      { text: "mango",      category: "food", difficultyId: "EASY" },
      { text: "hot dog",    category: "food", difficultyId: "EASY" },
      { text: "hamburger",  category: "food", difficultyId: "EASY" },
      { text: "ice cream",  category: "food", difficultyId: "EASY" },
      { text: "chocolate",  category: "food", difficultyId: "EASY" },
      { text: "cookie",     category: "food", difficultyId: "EASY" },
      { text: "pancake",    category: "food", difficultyId: "MEDIUM" },
      { text: "cupcake",    category: "food", difficultyId: "MEDIUM" },
      { text: "watermelon", category: "food", difficultyId: "MEDIUM" },
      { text: "pineapple",  category: "food", difficultyId: "MEDIUM" },
      { text: "blueberry",  category: "food", difficultyId: "MEDIUM" },
      { text: "omelette",   category: "food", difficultyId: "MEDIUM" },
      { text: "noodle",     category: "food", difficultyId: "MEDIUM" },
      { text: "spring roll",category: "food", difficultyId: "MEDIUM" },
      { text: "cheesecake", category: "food", difficultyId: "HARD" },
      { text: "kebab",      category: "food", difficultyId: "HARD" },
      { text: "baguette",   category: "food", difficultyId: "HARD" },
      { text: "tiramisu",   category: "food", difficultyId: "HARD" },
      { text: "dumplings",  category: "food", difficultyId: "HARD" },

      // ── Extra English — places ─────────────────────────────────────────────
      { text: "igloo",      category: "places", difficultyId: "EASY" },
      { text: "pyramid",    category: "places", difficultyId: "EASY" },
      { text: "farm",       category: "places", difficultyId: "EASY" },
      { text: "hospital",   category: "places", difficultyId: "EASY" },
      { text: "market",     category: "places", difficultyId: "EASY" },
      { text: "museum",     category: "places", difficultyId: "EASY" },
      { text: "zoo",        category: "places", difficultyId: "EASY" },
      { text: "garage",     category: "places", difficultyId: "EASY" },
      { text: "aquarium",   category: "places", difficultyId: "MEDIUM" },
      { text: "theater",    category: "places", difficultyId: "MEDIUM" },
      { text: "airport",    category: "places", difficultyId: "MEDIUM" },
      { text: "skyscraper", category: "places", difficultyId: "MEDIUM" },
      { text: "ruins",      category: "places", difficultyId: "MEDIUM" },
      { text: "treehouse",  category: "places", difficultyId: "MEDIUM" },
      { text: "maze",       category: "places", difficultyId: "MEDIUM" },
      { text: "spaceship",  category: "places", difficultyId: "HARD" },
      { text: "submarine base", category: "places", difficultyId: "HARD" },
      { text: "haunted house",  category: "places", difficultyId: "HARD" },

      // ── Extra English — actions ────────────────────────────────────────────
      { text: "read",       category: "actions", difficultyId: "EASY" },
      { text: "eat",        category: "actions", difficultyId: "EASY" },
      { text: "drink",      category: "actions", difficultyId: "EASY" },
      { text: "draw",       category: "actions", difficultyId: "EASY" },
      { text: "ride",       category: "actions", difficultyId: "EASY" },
      { text: "drive",      category: "actions", difficultyId: "EASY" },
      { text: "lift",       category: "actions", difficultyId: "EASY" },
      { text: "hug",        category: "actions", difficultyId: "EASY" },
      { text: "sneeze",     category: "actions", difficultyId: "MEDIUM" },
      { text: "yawn",       category: "actions", difficultyId: "MEDIUM" },
      { text: "trip",       category: "actions", difficultyId: "MEDIUM" },
      { text: "surf",       category: "actions", difficultyId: "MEDIUM" },
      { text: "skate",      category: "actions", difficultyId: "MEDIUM" },
      { text: "slide",      category: "actions", difficultyId: "MEDIUM" },
      { text: "dive",       category: "actions", difficultyId: "MEDIUM" },
      { text: "snore",      category: "actions", difficultyId: "HARD" },
      { text: "tiptoe",     category: "actions", difficultyId: "HARD" },
      { text: "shrug",      category: "actions", difficultyId: "HARD" },

      // ── Extra English — nature ─────────────────────────────────────────────
      { text: "cloud",      category: "nature", difficultyId: "EASY" },
      { text: "sun",        category: "nature", difficultyId: "EASY" },
      { text: "moon",       category: "nature", difficultyId: "EASY" },
      { text: "star",       category: "nature", difficultyId: "EASY" },
      { text: "tree",       category: "nature", difficultyId: "EASY" },
      { text: "flower",     category: "nature", difficultyId: "EASY" },
      { text: "snow",       category: "nature", difficultyId: "EASY" },
      { text: "rain",       category: "nature", difficultyId: "EASY" },
      { text: "wave",       category: "nature", difficultyId: "EASY" },
      { text: "waterfall",  category: "nature", difficultyId: "MEDIUM" },
      { text: "volcano",    category: "nature", difficultyId: "MEDIUM" },
      { text: "geyser",     category: "nature", difficultyId: "MEDIUM" },
      { text: "iceberg",    category: "nature", difficultyId: "MEDIUM" },
      { text: "mushroom",   category: "nature", difficultyId: "MEDIUM" },
      { text: "bamboo",     category: "nature", difficultyId: "HARD" },
      { text: "quicksand",  category: "nature", difficultyId: "HARD" },
      { text: "stalactite", category: "nature", difficultyId: "HARD" },

      // ── Extra English — sports ─────────────────────────────────────────────
      { text: "rugby",      category: "sports", difficultyId: "EASY" },
      { text: "baseball",   category: "sports", difficultyId: "EASY" },
      { text: "ping pong",  category: "sports", difficultyId: "EASY" },
      { text: "karate",     category: "sports", difficultyId: "MEDIUM" },
      { text: "judo",       category: "sports", difficultyId: "MEDIUM" },
      { text: "polo",       category: "sports", difficultyId: "MEDIUM" },
      { text: "lacrosse",   category: "sports", difficultyId: "HARD" },
      { text: "bobsled",    category: "sports", difficultyId: "HARD" },
      { text: "curling",    category: "sports", difficultyId: "HARD" },

      // ── Countries (English) ────────────────────────────────────────────────
      { text: "france",     category: "countries", difficultyId: "EASY" },
      { text: "germany",    category: "countries", difficultyId: "EASY" },
      { text: "italy",      category: "countries", difficultyId: "EASY" },
      { text: "spain",      category: "countries", difficultyId: "EASY" },
      { text: "japan",      category: "countries", difficultyId: "EASY" },
      { text: "china",      category: "countries", difficultyId: "EASY" },
      { text: "brazil",     category: "countries", difficultyId: "EASY" },
      { text: "mexico",     category: "countries", difficultyId: "EASY" },
      { text: "australia",  category: "countries", difficultyId: "EASY" },
      { text: "egypt",      category: "countries", difficultyId: "EASY" },
      { text: "india",      category: "countries", difficultyId: "EASY" },
      { text: "russia",     category: "countries", difficultyId: "EASY" },
      { text: "canada",     category: "countries", difficultyId: "EASY" },
      { text: "argentina",  category: "countries", difficultyId: "EASY" },
      { text: "england",    category: "countries", difficultyId: "EASY" },
      { text: "greece",     category: "countries", difficultyId: "EASY" },
      { text: "turkey",     category: "countries", difficultyId: "EASY" },
      { text: "thailand",   category: "countries", difficultyId: "EASY" },
      { text: "morocco",    category: "countries", difficultyId: "EASY" },
      { text: "norway",     category: "countries", difficultyId: "MEDIUM" },
      { text: "sweden",     category: "countries", difficultyId: "MEDIUM" },
      { text: "denmark",    category: "countries", difficultyId: "MEDIUM" },
      { text: "finland",    category: "countries", difficultyId: "MEDIUM" },
      { text: "ireland",    category: "countries", difficultyId: "MEDIUM" },
      { text: "portugal",   category: "countries", difficultyId: "MEDIUM" },
      { text: "poland",     category: "countries", difficultyId: "MEDIUM" },
      { text: "austria",    category: "countries", difficultyId: "MEDIUM" },
      { text: "belgium",    category: "countries", difficultyId: "MEDIUM" },
      { text: "switzerland",category: "countries", difficultyId: "MEDIUM" },
      { text: "netherlands",category: "countries", difficultyId: "MEDIUM" },
      { text: "vietnam",    category: "countries", difficultyId: "MEDIUM" },
      { text: "indonesia",  category: "countries", difficultyId: "MEDIUM" },
      { text: "colombia",   category: "countries", difficultyId: "MEDIUM" },
      { text: "peru",       category: "countries", difficultyId: "MEDIUM" },
      { text: "cuba",       category: "countries", difficultyId: "MEDIUM" },
      { text: "chile",      category: "countries", difficultyId: "MEDIUM" },
      { text: "jamaica",    category: "countries", difficultyId: "MEDIUM" },
      { text: "iceland",    category: "countries", difficultyId: "HARD" },
      { text: "singapore",  category: "countries", difficultyId: "HARD" },
      { text: "new zealand",category: "countries", difficultyId: "HARD" },
      { text: "south korea",category: "countries", difficultyId: "HARD" },
      { text: "saudi arabia",category: "countries", difficultyId: "HARD" },
    ],
    skipDuplicates: true,
  });

  // ── French words ──────────────────────────────────────────────────────────
  await prisma.word.createMany({
    data: [
      // Animaux (animals)
      { text: "chien",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "chat",       language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "lapin",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "cheval",     language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "vache",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "cochon",     language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "mouton",     language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "canard",     language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "poule",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "grenouille", language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "serpent",    language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "ours",       language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "loup",       language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "renard",     language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "tigre",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "singe",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "cerf",       language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "aigle",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "hibou",      language: "fr", category: "animals",  difficultyId: "EASY" },
      { text: "dauphin",    language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "baleine",    language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "requin",     language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "papillon",   language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "escargot",   language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "araignée",   language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "abeille",    language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "flamant",    language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "crocodile",  language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "girafe",     language: "fr", category: "animals",  difficultyId: "MEDIUM" },
      { text: "kangourou",  language: "fr", category: "animals",  difficultyId: "HARD" },
      { text: "chauve-souris", language: "fr", category: "animals", difficultyId: "HARD" },
      { text: "hippopotame",language: "fr", category: "animals",  difficultyId: "HARD" },
      { text: "platypus",   language: "fr", category: "animals",  difficultyId: "HARD" },

      // Objets (objects)
      { text: "chaise",     language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "livre",      language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "lampe",      language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "miroir",     language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "clé",        language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "marteau",    language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "chapeau",    language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "sac",        language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "bouteille",  language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "stylo",      language: "fr", category: "objects",  difficultyId: "EASY" },
      { text: "horloge",    language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "parapluie",  language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "couronne",   language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "épée",       language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "lunettes",   language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "guitare",    language: "fr", category: "objects",  difficultyId: "MEDIUM" },
      { text: "boussole",   language: "fr", category: "objects",  difficultyId: "HARD" },
      { text: "microscope", language: "fr", category: "objects",  difficultyId: "HARD" },
      { text: "télescope",  language: "fr", category: "objects",  difficultyId: "HARD" },

      // Nourriture (food)
      { text: "pain",       language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "pomme",      language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "gâteau",     language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "fromage",    language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "soupe",      language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "tarte",      language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "glace",      language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "beurre",     language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "tomate",     language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "oignon",     language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "carotte",    language: "fr", category: "food",     difficultyId: "EASY" },
      { text: "croissant",  language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "baguette",   language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "salade",     language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "champignon", language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "fraise",     language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "ananas",     language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "crepe",      language: "fr", category: "food",     difficultyId: "MEDIUM" },
      { text: "eclair",     language: "fr", category: "food",     difficultyId: "HARD" },
      { text: "macaron",    language: "fr", category: "food",     difficultyId: "HARD" },
      { text: "ratatouille",language: "fr", category: "food",     difficultyId: "HARD" },

      // Lieux (places)
      { text: "plage",      language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "forêt",      language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "école",      language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "château",    language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "marché",     language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "montagne",   language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "désert",     language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "village",    language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "île",        language: "fr", category: "places",   difficultyId: "EASY" },
      { text: "hôpital",    language: "fr", category: "places",   difficultyId: "MEDIUM" },
      { text: "bibliothèque", language: "fr", category: "places", difficultyId: "MEDIUM" },
      { text: "phare",      language: "fr", category: "places",   difficultyId: "MEDIUM" },
      { text: "volcan",     language: "fr", category: "places",   difficultyId: "MEDIUM" },
      { text: "grotte",     language: "fr", category: "places",   difficultyId: "MEDIUM" },
      { text: "pyramide",   language: "fr", category: "places",   difficultyId: "HARD" },
      { text: "cathédrale", language: "fr", category: "places",   difficultyId: "HARD" },

      // Actions (actions)
      { text: "courir",     language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "sauter",     language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "nager",      language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "voler",      language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "danser",     language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "chanter",    language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "dormir",     language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "manger",     language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "lire",       language: "fr", category: "actions",  difficultyId: "EASY" },
      { text: "peindre",    language: "fr", category: "actions",  difficultyId: "MEDIUM" },
      { text: "escalader",  language: "fr", category: "actions",  difficultyId: "MEDIUM" },
      { text: "pêcher",     language: "fr", category: "actions",  difficultyId: "MEDIUM" },
      { text: "creuser",    language: "fr", category: "actions",  difficultyId: "MEDIUM" },
      { text: "jongler",    language: "fr", category: "actions",  difficultyId: "HARD" },
      { text: "méditer",    language: "fr", category: "actions",  difficultyId: "HARD" },

      // Nature (nature)
      { text: "nuage",      language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "soleil",     language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "lune",       language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "étoile",     language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "arbre",      language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "fleur",      language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "rivière",    language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "arc-en-ciel",language: "fr", category: "nature",   difficultyId: "EASY" },
      { text: "tempête",    language: "fr", category: "nature",   difficultyId: "MEDIUM" },
      { text: "tornade",    language: "fr", category: "nature",   difficultyId: "MEDIUM" },
      { text: "aurore",     language: "fr", category: "nature",   difficultyId: "MEDIUM" },
      { text: "cascade",    language: "fr", category: "nature",   difficultyId: "MEDIUM" },
      { text: "iceberg",    language: "fr", category: "nature",   difficultyId: "HARD" },
      { text: "stalactite", language: "fr", category: "nature",   difficultyId: "HARD" },

      // Sports (sports)
      { text: "football",   language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "tennis",     language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "natation",   language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "cyclisme",   language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "boxe",       language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "ski",        language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "golf",       language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "rugby",      language: "fr", category: "sports",   difficultyId: "EASY" },
      { text: "basket",     language: "fr", category: "sports",   difficultyId: "MEDIUM" },
      { text: "volleyball", language: "fr", category: "sports",   difficultyId: "MEDIUM" },
      { text: "surf",       language: "fr", category: "sports",   difficultyId: "MEDIUM" },
      { text: "escalade",   language: "fr", category: "sports",   difficultyId: "MEDIUM" },
      { text: "escrime",    language: "fr", category: "sports",   difficultyId: "HARD" },
      { text: "triathlon",  language: "fr", category: "sports",   difficultyId: "HARD" },
      { text: "gymnastique", language: "fr", category: "sports",  difficultyId: "HARD" },

      // Vêtements (clothing)
      { text: "manteau",    language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "robe",       language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "chaussures", language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "cravate",    language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "écharpe",    language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "gants",      language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "pull",       language: "fr", category: "clothing",  difficultyId: "EASY" },
      { text: "casquette",  language: "fr", category: "clothing",  difficultyId: "MEDIUM" },
      { text: "imperméable",language: "fr", category: "clothing",  difficultyId: "MEDIUM" },
      { text: "kimono",     language: "fr", category: "clothing",  difficultyId: "HARD" },
      { text: "smoking",    language: "fr", category: "clothing",  difficultyId: "HARD" },

      // Pays (countries)
      { text: "france",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "allemagne",  language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "italie",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "espagne",    language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "japon",      language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "chine",      language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "brésil",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "mexique",    language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "australie",  language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "egypte",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "inde",       language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "russie",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "canada",     language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "grèce",      language: "fr", category: "countries", difficultyId: "EASY" },
      { text: "maroc",      language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "norvège",    language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "suède",      language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "suisse",     language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "portugal",   language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "belgique",   language: "fr", category: "countries", difficultyId: "MEDIUM" },
      { text: "islande",    language: "fr", category: "countries", difficultyId: "HARD" },
      { text: "singapour",  language: "fr", category: "countries", difficultyId: "HARD" },
    ],
    skipDuplicates: true,
  });

  // ── German words ──────────────────────────────────────────────────────────
  await prisma.word.createMany({
    data: [
      // Tiere (animals)
      { text: "Hund",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Katze",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Hase",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Pferd",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Kuh",        language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Schwein",    language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Schaf",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Ente",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Huhn",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Frosch",     language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Schlange",   language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Bär",        language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Wolf",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Fuchs",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Tiger",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Affe",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Adler",      language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Eule",       language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Fledermaus", language: "de", category: "animals",  difficultyId: "EASY" },
      { text: "Delfin",     language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Wal",        language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Hai",        language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Schmetterling", language: "de", category: "animals", difficultyId: "MEDIUM" },
      { text: "Schnecke",   language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Spinne",     language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Biene",      language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Flamingo",   language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Krokodil",   language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Giraffe",    language: "de", category: "animals",  difficultyId: "MEDIUM" },
      { text: "Känguru",    language: "de", category: "animals",  difficultyId: "HARD" },
      { text: "Nashorn",    language: "de", category: "animals",  difficultyId: "HARD" },
      { text: "Nilpferd",   language: "de", category: "animals",  difficultyId: "HARD" },
      { text: "Schimpanse", language: "de", category: "animals",  difficultyId: "HARD" },

      // Gegenstände (objects)
      { text: "Stuhl",      language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Buch",       language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Lampe",      language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Spiegel",    language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Schlüssel",  language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Hammer",     language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Hut",        language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Tasche",     language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Flasche",    language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Stift",      language: "de", category: "objects",  difficultyId: "EASY" },
      { text: "Uhr",        language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Regenschirm",language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Krone",      language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Schwert",    language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Brille",     language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Gitarre",    language: "de", category: "objects",  difficultyId: "MEDIUM" },
      { text: "Kompass",    language: "de", category: "objects",  difficultyId: "HARD" },
      { text: "Mikroskop",  language: "de", category: "objects",  difficultyId: "HARD" },
      { text: "Teleskop",   language: "de", category: "objects",  difficultyId: "HARD" },

      // Essen (food)
      { text: "Brot",       language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Apfel",      language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Kuchen",     language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Käse",       language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Suppe",      language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Butter",     language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Tomate",     language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Zwiebel",    language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Karotte",    language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Wurst",      language: "de", category: "food",     difficultyId: "EASY" },
      { text: "Brezel",     language: "de", category: "food",     difficultyId: "MEDIUM" },
      { text: "Salat",      language: "de", category: "food",     difficultyId: "MEDIUM" },
      { text: "Pilz",       language: "de", category: "food",     difficultyId: "MEDIUM" },
      { text: "Erdbeere",   language: "de", category: "food",     difficultyId: "MEDIUM" },
      { text: "Ananas",     language: "de", category: "food",     difficultyId: "MEDIUM" },
      { text: "Pfannkuchen",language: "de", category: "food",     difficultyId: "HARD" },
      { text: "Schnitzel",  language: "de", category: "food",     difficultyId: "HARD" },
      { text: "Strudel",    language: "de", category: "food",     difficultyId: "HARD" },

      // Orte (places)
      { text: "Strand",     language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Wald",       language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Schule",     language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Burg",       language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Markt",      language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Berg",       language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Wüste",      language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Dorf",       language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Insel",      language: "de", category: "places",   difficultyId: "EASY" },
      { text: "Krankenhaus",language: "de", category: "places",   difficultyId: "MEDIUM" },
      { text: "Bibliothek", language: "de", category: "places",   difficultyId: "MEDIUM" },
      { text: "Leuchtturm", language: "de", category: "places",   difficultyId: "MEDIUM" },
      { text: "Vulkan",     language: "de", category: "places",   difficultyId: "MEDIUM" },
      { text: "Höhle",      language: "de", category: "places",   difficultyId: "MEDIUM" },
      { text: "Pyramide",   language: "de", category: "places",   difficultyId: "HARD" },
      { text: "Kathedrale", language: "de", category: "places",   difficultyId: "HARD" },

      // Aktionen (actions)
      { text: "laufen",     language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "springen",   language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "schwimmen",  language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "fliegen",    language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "tanzen",     language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "singen",     language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "schlafen",   language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "essen",      language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "lesen",      language: "de", category: "actions",  difficultyId: "EASY" },
      { text: "malen",      language: "de", category: "actions",  difficultyId: "MEDIUM" },
      { text: "klettern",   language: "de", category: "actions",  difficultyId: "MEDIUM" },
      { text: "angeln",     language: "de", category: "actions",  difficultyId: "MEDIUM" },
      { text: "graben",     language: "de", category: "actions",  difficultyId: "MEDIUM" },
      { text: "jonglieren", language: "de", category: "actions",  difficultyId: "HARD" },
      { text: "meditieren", language: "de", category: "actions",  difficultyId: "HARD" },

      // Natur (nature)
      { text: "Wolke",      language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Sonne",      language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Mond",       language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Stern",      language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Baum",       language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Blume",      language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Fluss",      language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Regenbogen", language: "de", category: "nature",   difficultyId: "EASY" },
      { text: "Sturm",      language: "de", category: "nature",   difficultyId: "MEDIUM" },
      { text: "Tornado",    language: "de", category: "nature",   difficultyId: "MEDIUM" },
      { text: "Polarlicht", language: "de", category: "nature",   difficultyId: "MEDIUM" },
      { text: "Wasserfall", language: "de", category: "nature",   difficultyId: "MEDIUM" },
      { text: "Eisberg",    language: "de", category: "nature",   difficultyId: "HARD" },
      { text: "Stalaktit",  language: "de", category: "nature",   difficultyId: "HARD" },

      // Sport (sports)
      { text: "Fußball",    language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Tennis",     language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Schwimmen",  language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Radfahren",  language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Boxen",      language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Skifahren",  language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Golf",       language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Rugby",      language: "de", category: "sports",   difficultyId: "EASY" },
      { text: "Basketball", language: "de", category: "sports",   difficultyId: "MEDIUM" },
      { text: "Volleyball", language: "de", category: "sports",   difficultyId: "MEDIUM" },
      { text: "Surfen",     language: "de", category: "sports",   difficultyId: "MEDIUM" },
      { text: "Klettern",   language: "de", category: "sports",   difficultyId: "MEDIUM" },
      { text: "Fechten",    language: "de", category: "sports",   difficultyId: "HARD" },
      { text: "Triathlon",  language: "de", category: "sports",   difficultyId: "HARD" },
      { text: "Turnen",     language: "de", category: "sports",   difficultyId: "HARD" },

      // Kleidung (clothing)
      { text: "Mantel",     language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Kleid",      language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Schuhe",     language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Krawatte",   language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Schal",      language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Handschuhe", language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Pullover",   language: "de", category: "clothing",  difficultyId: "EASY" },
      { text: "Mütze",      language: "de", category: "clothing",  difficultyId: "MEDIUM" },
      { text: "Regenmantel",language: "de", category: "clothing",  difficultyId: "MEDIUM" },
      { text: "Kimono",     language: "de", category: "clothing",  difficultyId: "HARD" },
      { text: "Smoking",    language: "de", category: "clothing",  difficultyId: "HARD" },

      // Länder (countries)
      { text: "Frankreich", language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Deutschland",language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Italien",    language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Spanien",    language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Japan",      language: "de", category: "countries", difficultyId: "EASY" },
      { text: "China",      language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Brasilien",  language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Mexiko",     language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Australien", language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Ägypten",    language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Indien",     language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Russland",   language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Kanada",     language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Griechenland", language: "de", category: "countries", difficultyId: "EASY" },
      { text: "Marokko",    language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Norwegen",   language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Schweden",   language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Schweiz",    language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Portugal",   language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Belgien",    language: "de", category: "countries", difficultyId: "MEDIUM" },
      { text: "Island",     language: "de", category: "countries", difficultyId: "HARD" },
      { text: "Singapur",   language: "de", category: "countries", difficultyId: "HARD" },
    ],
    skipDuplicates: true,
  });

  console.log("✓ Seed complete — all lookup tables populated.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
